// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin/integrations/baidu-pan" | "/admin/users" | "/agent" | "/chat" | "/chat/[sessionId]" | "/datasource" | "/diary" | "/docs" | "/func-docs" | "/func-docs/[docId]" | "/func-docs/[docId]/features" | "/groups" | "/hot-search" | "/knowledge/mastery" | "/knowledge/personal" | "/knowledge/sets" | "/life-countdown" | "/mcp-server" | "/mcp-tool" | "/menu" | "/notification/send" | "/notifications/exception-logs" | "/open/baidu-pan/auth/callback" | "/orchestration" | "/orchestration/[workflowId]" | "/price-monitor" | "/schedule" | "/statistics-center/question-bank" | "/subjects" | "/system/roles" | "/todo" | "/vocabulary" | "/vocabulary/proficiency" | "/vocabulary/review" | "/wrong-question" | "/wxapp"
type AppRouteHandlerRoutes = "/api/baidu-pan/auth/authorize-url" | "/api/baidu-pan/auth/status" | "/api/baidu-pan/auth/unbind" | "/api/datasources" | "/api/datasources/[id]" | "/api/datasources/[id]/schema/collect" | "/api/datasources/[id]/schema/preview" | "/api/datasources/[id]/schemas" | "/api/datasources/[id]/test" | "/api/datasources/validate" | "/api/docs" | "/api/docs/[id]" | "/api/life-countdown/current" | "/api/life-countdown/generate-warning" | "/api/life-countdown/save" | "/api/notification/jobs/[jobId]/logs/stream" | "/api/notification/recipients" | "/api/notification/send" | "/api/notifications/exception-logs" | "/api/notifications/exception-logs/[id]/retry" | "/api/project/requirement/[id]/analyze" | "/api/project/requirement/[id]/lifecycle" | "/api/project/requirement/[id]/review" | "/api/project/requirement/create" | "/api/project/requirement/delete/[id]" | "/api/project/requirement/get/[id]" | "/api/project/requirement/history-options" | "/api/project/requirement/search" | "/api/project/requirement/update" | "/api/schedule/events" | "/api/schedule/events/[id]" | "/api/schedule/events/[id]/complete" | "/api/statistics/themes/knowledge-mastery/dashboard" | "/api/statistics/themes/question-bank/dashboard" | "/api/statistics/themes/vocabulary-proficiency/dashboard"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin/integrations/baidu-pan": {}
  "/admin/users": {}
  "/agent": {}
  "/api/baidu-pan/auth/authorize-url": {}
  "/api/baidu-pan/auth/status": {}
  "/api/baidu-pan/auth/unbind": {}
  "/api/datasources": {}
  "/api/datasources/[id]": { "id": string; }
  "/api/datasources/[id]/schema/collect": { "id": string; }
  "/api/datasources/[id]/schema/preview": { "id": string; }
  "/api/datasources/[id]/schemas": { "id": string; }
  "/api/datasources/[id]/test": { "id": string; }
  "/api/datasources/validate": {}
  "/api/docs": {}
  "/api/docs/[id]": { "id": string; }
  "/api/life-countdown/current": {}
  "/api/life-countdown/generate-warning": {}
  "/api/life-countdown/save": {}
  "/api/notification/jobs/[jobId]/logs/stream": { "jobId": string; }
  "/api/notification/recipients": {}
  "/api/notification/send": {}
  "/api/notifications/exception-logs": {}
  "/api/notifications/exception-logs/[id]/retry": { "id": string; }
  "/api/project/requirement/[id]/analyze": { "id": string; }
  "/api/project/requirement/[id]/lifecycle": { "id": string; }
  "/api/project/requirement/[id]/review": { "id": string; }
  "/api/project/requirement/create": {}
  "/api/project/requirement/delete/[id]": { "id": string; }
  "/api/project/requirement/get/[id]": { "id": string; }
  "/api/project/requirement/history-options": {}
  "/api/project/requirement/search": {}
  "/api/project/requirement/update": {}
  "/api/schedule/events": {}
  "/api/schedule/events/[id]": { "id": string; }
  "/api/schedule/events/[id]/complete": { "id": string; }
  "/api/statistics/themes/knowledge-mastery/dashboard": {}
  "/api/statistics/themes/question-bank/dashboard": {}
  "/api/statistics/themes/vocabulary-proficiency/dashboard": {}
  "/chat": {}
  "/chat/[sessionId]": { "sessionId": string; }
  "/datasource": {}
  "/diary": {}
  "/docs": {}
  "/func-docs": {}
  "/func-docs/[docId]": { "docId": string; }
  "/func-docs/[docId]/features": { "docId": string; }
  "/groups": {}
  "/hot-search": {}
  "/knowledge/mastery": {}
  "/knowledge/personal": {}
  "/knowledge/sets": {}
  "/life-countdown": {}
  "/mcp-server": {}
  "/mcp-tool": {}
  "/menu": {}
  "/notification/send": {}
  "/notifications/exception-logs": {}
  "/open/baidu-pan/auth/callback": {}
  "/orchestration": {}
  "/orchestration/[workflowId]": { "workflowId": string; }
  "/price-monitor": {}
  "/schedule": {}
  "/statistics-center/question-bank": {}
  "/subjects": {}
  "/system/roles": {}
  "/todo": {}
  "/vocabulary": {}
  "/vocabulary/proficiency": {}
  "/vocabulary/review": {}
  "/wrong-question": {}
  "/wxapp": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
