// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/admin/integrations/baidu-pan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/integrations/baidu-pan">> = Specific
  const handler = {} as typeof import("../../src/app/admin/integrations/baidu-pan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../src/app/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/agent/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agent">> = Specific
  const handler = {} as typeof import("../../src/app/agent/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/chat/[sessionId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/chat/[sessionId]">> = Specific
  const handler = {} as typeof import("../../src/app/chat/[sessionId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/chat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/chat">> = Specific
  const handler = {} as typeof import("../../src/app/chat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/datasource/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/datasource">> = Specific
  const handler = {} as typeof import("../../src/app/datasource/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/diary/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/diary">> = Specific
  const handler = {} as typeof import("../../src/app/diary/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/docs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs">> = Specific
  const handler = {} as typeof import("../../src/app/docs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/func-docs/[docId]/features/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/func-docs/[docId]/features">> = Specific
  const handler = {} as typeof import("../../src/app/func-docs/[docId]/features/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/func-docs/[docId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/func-docs/[docId]">> = Specific
  const handler = {} as typeof import("../../src/app/func-docs/[docId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/func-docs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/func-docs">> = Specific
  const handler = {} as typeof import("../../src/app/func-docs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/groups/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/groups">> = Specific
  const handler = {} as typeof import("../../src/app/groups/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/hot-search/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hot-search">> = Specific
  const handler = {} as typeof import("../../src/app/hot-search/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/knowledge/mastery/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/knowledge/mastery">> = Specific
  const handler = {} as typeof import("../../src/app/knowledge/mastery/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/knowledge/personal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/knowledge/personal">> = Specific
  const handler = {} as typeof import("../../src/app/knowledge/personal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/knowledge/sets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/knowledge/sets">> = Specific
  const handler = {} as typeof import("../../src/app/knowledge/sets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/life-countdown/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/life-countdown">> = Specific
  const handler = {} as typeof import("../../src/app/life-countdown/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/mcp-server/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mcp-server">> = Specific
  const handler = {} as typeof import("../../src/app/mcp-server/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/mcp-tool/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mcp-tool">> = Specific
  const handler = {} as typeof import("../../src/app/mcp-tool/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/menu/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/menu">> = Specific
  const handler = {} as typeof import("../../src/app/menu/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/notification/send/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/notification/send">> = Specific
  const handler = {} as typeof import("../../src/app/notification/send/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/notifications/exception-logs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/notifications/exception-logs">> = Specific
  const handler = {} as typeof import("../../src/app/notifications/exception-logs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/open/baidu-pan/auth/callback/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/open/baidu-pan/auth/callback">> = Specific
  const handler = {} as typeof import("../../src/app/open/baidu-pan/auth/callback/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/orchestration/[workflowId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orchestration/[workflowId]">> = Specific
  const handler = {} as typeof import("../../src/app/orchestration/[workflowId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/orchestration/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orchestration">> = Specific
  const handler = {} as typeof import("../../src/app/orchestration/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/price-monitor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/price-monitor">> = Specific
  const handler = {} as typeof import("../../src/app/price-monitor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/schedule/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/schedule">> = Specific
  const handler = {} as typeof import("../../src/app/schedule/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/statistics-center/question-bank/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/statistics-center/question-bank">> = Specific
  const handler = {} as typeof import("../../src/app/statistics-center/question-bank/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/subjects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/subjects">> = Specific
  const handler = {} as typeof import("../../src/app/subjects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/system/roles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/system/roles">> = Specific
  const handler = {} as typeof import("../../src/app/system/roles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/todo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/todo">> = Specific
  const handler = {} as typeof import("../../src/app/todo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/vocabulary/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vocabulary">> = Specific
  const handler = {} as typeof import("../../src/app/vocabulary/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/vocabulary/proficiency/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vocabulary/proficiency">> = Specific
  const handler = {} as typeof import("../../src/app/vocabulary/proficiency/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/vocabulary/review/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vocabulary/review">> = Specific
  const handler = {} as typeof import("../../src/app/vocabulary/review/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/wrong-question/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wrong-question">> = Specific
  const handler = {} as typeof import("../../src/app/wrong-question/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/wxapp/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wxapp">> = Specific
  const handler = {} as typeof import("../../src/app/wxapp/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/baidu-pan/auth/authorize-url/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/baidu-pan/auth/authorize-url">> = Specific
  const handler = {} as typeof import("../../src/app/api/baidu-pan/auth/authorize-url/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/baidu-pan/auth/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/baidu-pan/auth/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/baidu-pan/auth/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/baidu-pan/auth/unbind/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/baidu-pan/auth/unbind">> = Specific
  const handler = {} as typeof import("../../src/app/api/baidu-pan/auth/unbind/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/datasources/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/datasources/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/datasources/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/datasources/[id]/schema/collect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/datasources/[id]/schema/collect">> = Specific
  const handler = {} as typeof import("../../src/app/api/datasources/[id]/schema/collect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/datasources/[id]/schema/preview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/datasources/[id]/schema/preview">> = Specific
  const handler = {} as typeof import("../../src/app/api/datasources/[id]/schema/preview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/datasources/[id]/schemas/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/datasources/[id]/schemas">> = Specific
  const handler = {} as typeof import("../../src/app/api/datasources/[id]/schemas/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/datasources/[id]/test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/datasources/[id]/test">> = Specific
  const handler = {} as typeof import("../../src/app/api/datasources/[id]/test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/datasources/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/datasources">> = Specific
  const handler = {} as typeof import("../../src/app/api/datasources/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/datasources/validate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/datasources/validate">> = Specific
  const handler = {} as typeof import("../../src/app/api/datasources/validate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/docs/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/docs/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/docs/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/docs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/docs">> = Specific
  const handler = {} as typeof import("../../src/app/api/docs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/life-countdown/current/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/life-countdown/current">> = Specific
  const handler = {} as typeof import("../../src/app/api/life-countdown/current/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/life-countdown/generate-warning/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/life-countdown/generate-warning">> = Specific
  const handler = {} as typeof import("../../src/app/api/life-countdown/generate-warning/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/life-countdown/save/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/life-countdown/save">> = Specific
  const handler = {} as typeof import("../../src/app/api/life-countdown/save/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notification/jobs/[jobId]/logs/stream/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notification/jobs/[jobId]/logs/stream">> = Specific
  const handler = {} as typeof import("../../src/app/api/notification/jobs/[jobId]/logs/stream/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notification/recipients/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notification/recipients">> = Specific
  const handler = {} as typeof import("../../src/app/api/notification/recipients/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notification/send/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notification/send">> = Specific
  const handler = {} as typeof import("../../src/app/api/notification/send/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/exception-logs/[id]/retry/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/exception-logs/[id]/retry">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/exception-logs/[id]/retry/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/exception-logs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/exception-logs">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/exception-logs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/project/requirement/[id]/analyze/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/project/requirement/[id]/analyze">> = Specific
  const handler = {} as typeof import("../../src/app/api/project/requirement/[id]/analyze/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/project/requirement/[id]/lifecycle/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/project/requirement/[id]/lifecycle">> = Specific
  const handler = {} as typeof import("../../src/app/api/project/requirement/[id]/lifecycle/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/project/requirement/[id]/review/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/project/requirement/[id]/review">> = Specific
  const handler = {} as typeof import("../../src/app/api/project/requirement/[id]/review/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/project/requirement/create/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/project/requirement/create">> = Specific
  const handler = {} as typeof import("../../src/app/api/project/requirement/create/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/project/requirement/delete/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/project/requirement/delete/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/project/requirement/delete/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/project/requirement/get/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/project/requirement/get/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/project/requirement/get/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/project/requirement/history-options/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/project/requirement/history-options">> = Specific
  const handler = {} as typeof import("../../src/app/api/project/requirement/history-options/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/project/requirement/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/project/requirement/search">> = Specific
  const handler = {} as typeof import("../../src/app/api/project/requirement/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/project/requirement/update/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/project/requirement/update">> = Specific
  const handler = {} as typeof import("../../src/app/api/project/requirement/update/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/schedule/events/[id]/complete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/schedule/events/[id]/complete">> = Specific
  const handler = {} as typeof import("../../src/app/api/schedule/events/[id]/complete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/schedule/events/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/schedule/events/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/schedule/events/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/schedule/events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/schedule/events">> = Specific
  const handler = {} as typeof import("../../src/app/api/schedule/events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/statistics/themes/knowledge-mastery/dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/statistics/themes/knowledge-mastery/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/api/statistics/themes/knowledge-mastery/dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/statistics/themes/question-bank/dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/statistics/themes/question-bank/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/api/statistics/themes/question-bank/dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/statistics/themes/vocabulary-proficiency/dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/statistics/themes/vocabulary-proficiency/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/api/statistics/themes/vocabulary-proficiency/dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
